### ISSUE TITLE
Unable to enable

### ISSUE THREAD

**Issue by zvermashine** [LibreCodeCoop/LSNextcloud#3]
www-data@93d07876f779:~/html/apps/LSNextcloud$ make all
rm -rf vendor/
rm -rf build
No composer command available, downloading a copy from the web
mkdir -p /var/www/html/apps/LSNextcloud/build/tools
curl -sS https://getcomposer.org/installer | php
All settings correct for using Composer
Downloading...

Composer (version 2.5.5) successfully installed to: /var/www/html/apps/LSNextcloud/composer.phar
Use it: php composer.phar

mv composer.phar /var/www/html/apps/LSNextcloud/build/tools
php /var/www/html/apps/LSNextcloud/build/tools/composer.phar install --prefer-dist
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
Package operations: 10 installs, 0 updates, 0 removals
  - Installing sabre/uri (2.2.1): Extracting archive
  - Installing sabre/xml (2.2.3): Extracting archive
  - Installing sabre/vobject (4.3.5): Extracting archive
  - Installing sabre/event (5.1.2): Extracting archive
  - Installing sabre/http (5.1.1): Extracting archive
  - Installing psr/log (1.1.3): Extracting archive
  - Installing sabre/dav (4.1.5): Extracting archive
  - Installing league/mime-type-detection (1.7.0): Extracting archive
  - Installing league/flysystem (1.1.3): Extracting archive
  - Installing league/flysystem-webdav (1.0.9): Extracting archive
Generating autoload files
2 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
www-data@93d07876f779:~/html/apps/LSNextcloud$ cd ../../

www-data@93d07876f779:~/html$ php occ app:install LSNextcloud
LSNextcloud already installed
www-data@93d07876f779:~/html$ php occ app:enable LSNextcloud
App "LSNextcloud" cannot be installed because appinfo file cannot be read.
www-data@93d07876f779:~/html$ php occ app:list
Enabled:
  - activity: 2.17.0
  - bruteforcesettings: 2.5.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - impersonate: 1.12.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - onlyoffice: 7.8.0
  - password_policy: 1.15.0
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.4
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - encryption
  - files_accesscontrol: 1.15.1
  - files_external
  - login_notes: 1.2.0
  - suspicious_login
  - twofactor_totp
  - user_ldap

**Comment by vitormattos** [comment]
This plugin is to be used at LimeSurvey side, not as Nextcloud app.

Setup this plugin in your LimeSurvey instance.
